package com.trendythread.app.constants;

public interface IRedisConstant {

	String REDIS_BLOGGER_ID = "REDIS:BLOGGER:ID:";

	String REDIS_BLOGGER_EMAIL = "REDIS:BLOGGER:EMAIL:";

	String REDIS_ALL_BLOGGERS_CACHE = "REDIS:ALL:BLOGGERS";

	String REDIS_CATEGORY = "REDIS:CATEGORY:";

	String REDIS_CATEGORY_ID = REDIS_CATEGORY.concat("ID:");

	String REDIS_CATEGORY_FEATURED = REDIS_CATEGORY.concat("FEATURED");

	String REDIS_CATEGORY_KEYWORD = REDIS_CATEGORY.concat("KEYWORD:");

	String REDIS_ALL_CATEGORY_CACHE = "REDIS:ALL:CATEGORIES";

	String REDIS_POST = "REDIS:POST:";

	String REDIS_POST_ID = REDIS_POST.concat("ID:");

	String REDIS_POST_ALL = REDIS_POST.concat("ALL");

	String REDIS_POST_LATEST = REDIS_POST.concat("LATEST");

	String REDIS_POST_CATEGORY = REDIS_POST.concat("CATEGORY:");

	String REDIS_POST_BLOGGER = REDIS_POST.concat("BLOGGER:");

	String REDIS_POST_USER = REDIS_POST.concat("USER:");

	String REDIS_POST_KEYWORD = REDIS_POST.concat("KEYWORD:");

	String REDIS_COMMENT = "REDIS:COMMENT:";

	String REDIS_COMMENT_POST = REDIS_COMMENT.concat("POST:");

	String REDIS_COMMENT_LIST_SUFFIX = ":LIST";

	String REDIS_COMMENT_ID_SUFFIX = ":ID:";

	String REDIS_KEY_PAGE_CONSTANT = ":page:";

	String REDIS_KEY_SIZE_CONSTANT = ":size:";

	String REDIS_KEY_SORT_BY_CONSTANT = ":sortBy:";

	String REDIS_KEY_SORT_DIRECTION_CONSTANT = ":sortDir:";

	String REDIS_KEY_LIMIT_CONSTANT = ":limit:";
}