server:
  port: 8079

spring:

  application:
    name: TrendyThread

  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.mntswotqhnptsbfmsyep&password=8BLyQ-w*7Z9kLmD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

