server:
  port: 8079

spring:

  application:
    name: TrendyThread

  datasource:
    url: jdbc:postgresql://localhost:5432/blogapp
    username: blog
    password: blog
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

